import {
  arbitrum,
  arbitrumGoerli,
  mainnet,
  polygon,
  polygonMumbai,
  optimism,
  optimismGoerli,
  sepolia,
  ronin,
  saigon,
  aurora,
  avalanche,
  base,
  bsc,
  celo,
  gnosis,
  ink,
  inkSepolia,
  zkSync,
  zora,
  creditchain,
  creditchainTestnet,
} from './chains'

export const constants = {
  chains: [
    creditchain,
    creditchainTestnet,
    arbitrum,
    arbitrumGoerli,
    mainnet,
    polygon,
    polygonMumbai,
    optimism,
    optimismGoerli,
    sepolia,
    ronin,
    saigon,
    aurora,
    avalanche,
    base,
    bsc,
    celo,
    gnosis,
    ink,
    inkSepolia,
    zkSync,
    zora,
  ],
  // @ts-ignore
  PROJECT_ID: WALLET_CONNECT_PROJECT_ID,
  METADATA: {
    name: 'Forge',
    description: 'CreditChain-native smart contract studio for EVM development.',
    url: 'https://forge.creditchain.org/',
    icons: ['https://forge.creditchain.org/assets/img/creditchain-logo.png'],
  }
}
